### PR TITLE
Multi Renderer Plotting

### PR DESCRIPTION
**Pull request by akaszynski**
``vtki`` can now plot multiple renderers in the same render window.  Each renderer is independent from each other and the camera can be controlled individually.  This involved moving lots of code out of ``plotter`` into ``renderer``, which is actually a good thing since ``plotter.py`` was getting quite long.

@banesullivan, I'd like you to test this on your end as it's a big change.  Nothing should change if your plotter shape remains as default ``shape=(1,1)``, but I'd like you to verify it anyway.

```python
import vtki
from vtki import examples

plotter = vtki.Plotter(shape=(2, 2))

loc = (0, 0)
plotter.add_text('Render Window 0', loc=loc, font_size=30)
plotter.add_mesh(examples.load_globe(), loc=loc)
# plotter.add_axes()

# plotter.add_axes()
# plotter.set_background([1, 1, 1], loc)

loc = (0, 1)
plotter.add_text('Render Window 1', loc=loc, font_size=30)
plotter.add_mesh(vtki.Cube(), loc=loc, show_edges=True)
# plotter.add_axes()

loc = (1, 0)
plotter.add_text('Render Window 2', loc=loc, font_size=30)
sphere = vtki.Sphere()
plotter.add_mesh(sphere, loc=loc, scalars=sphere.points[:, 2])
plotter.add_scalar_bar('Z', vertical=True)
# plotter.add_axes()
# plotter.add_axes(interactive=True)


loc = (1, 1)
plotter.add_text('Render Window 3', loc=loc, font_size=30)
plotter.add_mesh(vtki.Cone(), color='g', loc=loc, show_edges=True)
plotter.add_bounds_axes(all_edges=True)
# plotter.add_mesh(vtki.Cube(), color='g', loc=loc, show_edges=True)
plotter.add_axes(interactive=True)
plotter.plot()
```
visualization toolkit - opengl_042

### CODE REVIEW

**Comment by banesullivan** [comment]
This is awesome!! All looks good on my end!

I have a few requested changes that you may have an easier time implementing than I:

- [ ] Could we add in visual separators to distinguish the different frames?
- [ ] Could we add an `active_loc` property to the plotter to give `matplotlib`-like syntax with a `p.subplot(0,1)` call to activate all calls on the plotter to default to `loc=(0,1)` after that so you don't have to explicitly pas `loc=loc` on every call?

### Issues:

I'm experiencing #97 again on this... which makes it impossible to control some of the subplots when using the background plotter.

ezgif com-video-to-gif

**Comment by akaszynski** [comment]
I can add those requests.  I can’t reproduce #97 on my end.  Does it happen when you resize the window?

**Comment by banesullivan** [comment]
It comes and goes... resizing doesn’t cause it for me

**Comment by banesullivan** [comment]
These changes broke something with texture mapping. See the example below where looking at the mesh from certain sides makes it transparent. I can't track down the issue.

```py
import vtki
import numpy as np
from vtki import examples

# create a rectangle vertices
vertices = np.array([[0, 0, 0],
                     [1, 0, 0],
                     [1, 0.5, 0],
                     [0, 0.5, 0],])

# mesh faces
faces = np.hstack([[3, 0, 1, 2],
                   [3, 0, 3, 2]]).astype(np.int8)

# Create simple texture coordinates
t_coords = np.array([[0, 0],
                    [1, 0],
                    [1, 1],
                    [0, 1]])
# Create the poly data
mesh = vtki.PolyData(vertices, faces)
# Attempt setting the texture coordinates
mesh.t_coords = t_coords

tex = examples.load_globe_texture()

p = vtki.BackgroundPlotter()

p.add_mesh(mesh, texture=tex)
```

ezgif com-video-to-gif

**Comment by akaszynski** [comment]
Fixed the issue with the texture.  I had automatically implemented backface culling, which cleans up dense mesh plotting but apparently has some side effects.  It's optional and defaults to False now.

**Comment by akaszynski** [comment]
Sorry, didn't mean to close.

**Comment by akaszynski** [comment]
Gah!

**Comment by akaszynski** [comment]
It just needs the ipython tools added for subplotting and we're good to go.  I'll make sure to click on "Comment" this time.

**Comment by banesullivan** [comment]
Why aren't the mappers and scalar bars managed by the `Renderer`?

**Comment by banesullivan** [comment]
Everything is looking good at this point! Let's try to address all the [`v0.17.0` milestones](https://github.com/vtkiorg/vtki/milestone/3) before merging to make sure the release will be stable.

**Comment by akaszynski** [comment]
Sounds good.  I'll wait to merge.

**Comment by banesullivan** [comment]
Actually, merging to `master` to put other changes in separate PRs

**Pull request merged**
