### PR TITLE
Resample with dataset

### PR DESCRIPTION
**Pull request by banesullivan**
Note this is an expansion of @ascillitoe's #171 

Add a filter to resample some other dataset onto a mesh's points... naming might be tricky here. Note that this will be implemented under `vtki.DataSetFilters` as a filtering method so you could call the function and pass it another mesh that you like to probe.

I like @ascillitoe's naming suggestion of `.interpolate` but I want to make sure this makes sense - @akaszynski, thoughts?

Usage:

```py
import vtki
from vtki import examples
import numpy as np

# Querry a grids points onto a sphere
mesh = vtki.Sphere(center=(4.5,4.5,4.5), radius=4.5)
data_to_probe = examples.load_uniform()

# Plot the two datasets
p = vtki.Plotter()
p.add_mesh(mesh, color=True)
p.add_mesh(data_to_probe, opacity=0.5)
p.show()
```

download

```py
# Run the algorithm
result = mesh.sample(data_to_probe)

# Plot result
result.plot(scalars='Spatial Point Data')
```

download

### CODE REVIEW

**Comment by akaszynski** [comment]
I think interpolate works, and so could interpolate_scalars (which is a little clearer, if a bit more verbose).

**Comment by banesullivan** [comment]
Not to get too verbose, but maybe even `interpolate_scalars_from` or `interpolate_from` to imply that the mesh object the filter is being called from will interpolate **from** the passed mesh's scalar data.

**Comment by banesullivan** [comment]
Also... this filter isn't technically interpolating - it's probing. So perhaps `interpolate` isn't appropriate?

**Comment by akaszynski** [comment]
Sample maybe?   Interpolate does indeed imply interpolation.

**Comment by banesullivan** [comment]
> Sample maybe? Interpolate does indeed imply interpolation.

I like `sample` as it suggests that the mesh is "sampling" the passed mesh

```py
mesh.sample(data_to_sample)
```

**Comment by akaszynski** [comment]
Agreed!

**Comment by ascillitoe** [comment]
Hi guys,First of all, just like to say thanks for all your work on vtki so far, it's been a super useful package for me.Secondly, apologies for the half done nature of my pull request, I accidentally submitted it sooner than I meant too! Re the name after thinking about it I agree sample makes much more sense than interpolate. Looking forward to contributing more!Regards,AshleyOn 16 Apr 2019 4:05 pm, Alex Kaszynski <notifications@github.com> wrote:Agreed!

**Comment by banesullivan** [comment]
> First of all, just like to say thanks for all your work on vtki so far, it's been a super useful package for me.

This is great to hear! It would be much appreciated if you could share any visualizations you make with `vtki` in your work to help us communicate what `vtki` can do! Perhaps consider sumbittiing examples when you have free time?

> Secondly, apologies for the half done nature of my pull request, I accidentally submitted it sooner than I meant too!

No worries, @ascillitoe! You actually didn't submit it... I was cleaning up some branches and saw your changes on the network graph. I made the PR and merged it because I was going to add that filter soon here.

**Pull request merged**
