### PR TITLE
[Travis]: Update build matrix

### PR DESCRIPTION
**Pull request by banesullivan**
Take a look at Travis - tests are split up into several jobs on each supported version of Python

### CODE REVIEW

**Comment by banesullivan** [comment]
Once again, AppVeyor is not starting jobs... I removed AppVeyor from required checks because the service itself is unpredictable - nothing we can do/change as users.

**Comment by akaszynski** [comment]
Appveyor isn't my favorite either.

It might be possible (with a bit of work) to test ``vtki`` on [Travis CI for Windows ](https://travis-ci.community/t/python-support-on-windows/241).

**Comment by akaszynski** [comment]
Does splitting up the tests reduce the total test time on Travis?

**Comment by banesullivan** [comment]
or maybe switch to azure pipelines like the folks over at mne-python?

**Comment by banesullivan** [comment]
i'm not actually sure... i did this because i thought it might

overall, these changes help make tracking down why a build failed a lot easier

**Comment by banesullivan** [comment]
i think its generally faster. hard to tell because the times reported by travis are a sum of all jobs happening in parallel

**Comment by akaszynski** [comment]
Ah, makes sense now.  The job breakdown is much easier to follow now that it's separated.

**Pull request merged**
