### PR TITLE
now using vtklightkit

### PR DESCRIPTION
**Pull request by akaszynski**
Lighting is better, but it's still not tracking the camera all the time.  It's possible to get the camera in a position where the lighting stays locked relative to the camera, but at other times it still moves around.  It's strange behavior and only occurs when the "y-axis" is perpendicular to the view direction.  Basically, if you're rotating around the y-axis, you get the expected lighting behavior.  Otherwise the lighting stays locked with the scene.

@banesullivan: Let me know if you see any reason why this isn't working.  According to the VTK documentation, you have to disable light following in the interactive renderer and enable it in the renderer.  I've done that:

```python
self.iren.LightFollowCameraOff()
self.renderer.LightFollowCameraOn()
```

axis_rot

### CODE REVIEW

**Comment by akaszynski** [comment]
Turns out if the mesh ``"Normals"`` in its point_arrays, it won't render correctly as a surface.  This is quite interesting, and means we'll have to either rename or remove this array before plotting.  Hopefully setting it as inactive will do the trick.

**Comment by banesullivan** [comment]
That's really weird... I suppose I noticed that the `Sphere` source always looked weird but the other dataset examples didn't but I never thought much of it.

**Comment by akaszynski** [comment]
Fixed the ``"Normals"`` bug.  Turns out you can pop and add it back in without losing the data or making it inactive.

lighting_fixed

**Comment by banesullivan** [comment]
This is perfect!! Thanks, @akaszynski!

**Pull request merged**
