### PR TITLE
JOSS Paper Submission

### PR DESCRIPTION
**Pull request by banesullivan**
This PR contains efforts to move `vtki` towards a ready state to submit to the Journal of Open Source Software (JOSS). 

Please see the [project board](https://github.com/akaszynski/vtki/projects/1) for status updates.

### CODE REVIEW

**Comment by banesullivan** [comment]
@akaszynski, the draft of the paper has been uploaded. Can you edit your information for author listing and provide edits.

Also, please see action items on the [project board](https://github.com/akaszynski/vtki/projects/1)

**Comment by banesullivan** [comment]
Majorly trimmed down the paper because API documentation in the paper should be minimal.

**Comment by banesullivan** [comment]
Note: here is another project using `vtki`: https://github.com/StructuralNeurobiologyLab/SyConn

**Comment by akaszynski** [comment]
Saw that.  It's great to see other modules using ``vtki``.  Hopefully once the API settles down we'll see more people using ``vtki``.

**Comment by banesullivan** [comment]
@akaszynski, on your comment:

> There are several recent papers from AFRL that include vtki figures.  It's late, and I'm not sure how cite in markdown.  I've included a bibtex file "ref.bib".  Would be great if we could use the references directly from there.

I've moved the citations into a consolidated bib file `paper.bib`. Citing will be handled by JOSS as long as you include `[@label]` where you'd like the citation (I've put a few other citations in there to mimic).

**Pull request merged**
