### PR TITLE
BUG: Escape char on re

### PR DESCRIPTION
**Pull request by larsoner**
Fixes un-escaped char.

### CODE REVIEW

**Comment by banesullivan** [comment]
Thanks for the fix, @larsoner! The failed build on Travis is a result of #169

**Comment by larsoner** [comment]
Can you enable AppVeyor for `gl-ci-helpers`? Want me to make a `vtkiorg` org with `gl-ci-helpers` project on Azure and add you to it?

**Comment by larsoner** [comment]
FYI I created the org and project https://dev.azure.com/vtkiorg/gl-ci-helpers, once I get permission from owners to link this to the GitHub project I can test Azure at least

**Comment by larsoner** [comment]
(I should probably not own the org, so let me know what emails to invite)

**Comment by banesullivan** [comment]
You can add me (banesulli@gmail.com) to the Azure project

**Pull request merged**
